#一般一个微服务一个端口号
server:
  port: 8001

spring:
  application:
    name: springcloud-payment-service #服务名称
    # sleuth 和zipkin配置相关
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率值介于 0 到 1 之间, 1 则表示全部采集
        probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/springcloud2020?characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: 123456

eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 入驻地址
      #defaultZone: http://localhost:7001/eureka/   #单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #集群版
  #服务名称
  instance:
    instance-id: payment8001
    #访问路径显示IP地址
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qcl.springcloud.entities  #所有entity别名所在包
